# Generated by Django 3.2 on 2023-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('caseid', models.IntegerField(default=0)),
                ('case_type', models.IntegerField(choices=[(0, 'Other')], default=0)),
                ('feature', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('runtime', models.CharField(blank=True, max_length=10, null=True)),
                ('timeout', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(default=None, max_length=5000, null=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
