# Generated by Django 3.2 on 2023-04-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(choices=[(0, 'waiting'), (1, 'running'), (2, 'pass'), (3, 'failed'), (4, 'abort'), (5, 'timeout'), (6, 'regression')], default=0)),
                ('result', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('run_step', models.IntegerField(choices=[(0, 'others'), (1, 'Prepare'), (2, 'Install'), (3, 'Testing'), (4, 'Finished'), (5, 'Aborted'), (6, 'Promoted'), (7, 'Blocked')], default=0)),
                ('run_status', models.BooleanField(default=True)),
                ('report_type', models.IntegerField(choices=[(0, 'others'), (1, 'pre-submission'), (2, 'daily'), (3, 'weekly'), (4, 'release')], default=0)),
                ('comment', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('test_case_run', models.ManyToManyField(default=None, related_name='testreports', to='testreports.TestCaseRun')),
            ],
        ),
    ]
