# Generated by Django 3.2 on 2023-05-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testreports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(blank=True, max_length=50, null=True)),
                ('component_value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='testreports',
            name='requester',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testreports',
            name='requester_ip',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testreports',
            name='component',
            field=models.ManyToManyField(default=None, related_name='testreports', to='testreports.ReportComponent'),
        ),
    ]
