# Generated by Django 3.2 on 2023-05-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testreports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaserun',
            name='gpu_info',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcaserun',
            name='guest_os',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcaserun',
            name='host_os',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
