# Generated by Django 3.2 on 2023-05-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testreports', '0002_auto_20230505_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaserun',
            name='testcase_run_type',
            field=models.IntegerField(choices=[(0, 'testcase'), (1, 'prepare'), (2, 'post')], default=0),
        ),
    ]
