# Generated by Django 3.2 on 2023-05-07 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testservers', '0001_initial'),
        ('testreports', '0003_testcaserun_testcase_run_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaserun',
            name='test_server',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='testcase_run', to='testservers.testservers'),
        ),
        migrations.AddField(
            model_name='testreports',
            name='test_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcaserun',
            name='testcase_run_type',
            field=models.IntegerField(choices=[(0, 'testrun'), (1, 'prepare'), (2, 'post')], default=0),
        ),
        migrations.CreateModel(
            name='TestServerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('testreports', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='testserver_record', to='testreports.testreports')),
                ('testserver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testserver_record', to='testservers.testservers')),
            ],
        ),
    ]
